---
title: "MSDS 6306: Case 1 "
author:
  - "Blake Holmes and Mel Schwan"
date: "June 20, 2019"
output: 
  html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(officer)
library(magrittr)
```

```{r injest data, echo=TRUE}
beerData<-read_csv("./Beers.csv")
breweryData<-read_csv("./Breweries.csv")
#Read baseline PowerPoint file
my_pres <- read_pptx('Anheuser-Busch_Breweries.pptx') 
```

```{r exploratory beerData analysis, echo=TRUE}
###b. What are the dimensions of the data?

glimpse(beerData)
summary(beerData)
#Name              Beer_ID            ABV               IBU           Brewery_id       Style               Ounces 

#beer summarized by style 
beerData %>%
  group_by(Style) %>%
  summarise(
    count= n(),
    IBU_count = sum(!is.na(IBU)),
    IBU_average = mean(IBU, na.rm = TRUE),
    IBU_sd = sd(IBU, na.rm = TRUE),
    ABV_count = sum(!is.na(ABV)),
    ABV_average = mean(ABV, na.rm = TRUE),
    ABV_sd = sd(ABV, na.rm = TRUE),
  ) 

beerData %>% 
  summarise_all(funs(sum(is.na(.)))) #count the number of NAs or blanks 
# ABV, IBU, Style have missing values 

beerData %>% 
    filter(is.na(ABV) |is.na(IBU) | is.na(Style)) 
#hmm what should be done about the missing values...
```

```{r exploratory brewery data aggregation by state, echo=TRUE}

glimpse(breweryData)
summary(breweryData)
#    Brew_ID          Name               City              State          

#Report the number of NA's in each column.
breweryData %>% 
  summarise_all(funs(sum(is.na(.))))#count the number of NAs or blanks
#no missing values 
```

```{r get population data, echo=TRUE}

library("httr")
library("jsonlite")

pop_url <- "https://api.census.gov/data/2018/pep/population?get=POP,GEONAME&for=state"

statepop_raw<- pop_url %>% 
  GET() %>% 
  content("text") %>%
  fromJSON(flatten=TRUE) %>% 
  as_tibble() %>% 
  slice(2:n())#remove the first row which is the labels 

names(statepop_raw)<-c("Population","State","State_ID")

statepop_raw$Population<- as.integer(statepop_raw$Population)

#add state abbreviations and DC/puerto rico
statepop_raw$State_Abb <- c(sort(c("DC",state.abb)),"PR")

```

```{r get state area data, echo=TRUE}
library(rvest)

area_url <-"https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_area"

statearea<- area_url %>% 
  read_html() %>% 
  html_node('#mw-content-text > div > table:nth-child(6)') %>% 
  html_table(header = F) %>% 
  slice(3:n()) %>% #remove the two rows which are labels
  select(X1,X6) %>% #keep the state area excluding water
  rename("State_name"="X1","Square_miles"="X6") %>% 
  mutate(Square_miles=as.integer(Square_miles))
  
```

#How many breweries in each state

```{r how many breweries in each state, echo=TRUE}
breweryData %>% 
  group_by(State) %>% 
  summarise(Number_of_breweries=n()) %>% 
  arrange(desc(Number_of_breweries)) 

# Merge beer data with the breweries data. Print the first 6 observations and the last six observations to check the merged file.
```


```{r merge data, echo=TRUE}

beer_brewery<-beerData %>%
  left_join(breweryData, by=c("Brewery_id"="Brew_ID"), suffix = c(".beer", ".brewery")) %>% 
  rename(Beer_name=Name.beer, Brewery_name=Name.brewery) %>% 
  #separate continuous variables into 3 groups, low/medium/high
  mutate(ABV_rating= cut_number(ABV, n = 3,labels=c("low","medium","high"))) %>% 
  mutate(IBU_rating= cut_number(IBU, n = 3,labels=c("low","medium","high"))) 
  
beer_brewery %>% 
  filter(is.na(Brewery_name)) 
#returns no results so all beers have a brewery

#Post merge data peak 
head(beer_brewery,6)
tail(beer_brewery,6)

```



```{r looking for bad data, echo=FALSE}
#looking for duplicated data in character vectors
lookForDupStrings <- function(string_arr){
  library(tidystringdist)
  string_arr %>%
    unique() %>% 
    tidy_comb_all() %>% 
    tidy_stringdist() %>% 
    arrange(osa)
}

lookForDupStrings(beer_brewery$Beer_name)
#there are a lot of simliar beer names, including those just differing by year.
#however it looks like good data
lookForDupStrings(beer_brewery$Style)
#these look pretty good actually

lookForDupStrings(beer_brewery$Brewery_name)
#TODO(bjh)there are duplicated breweries for cleanup, for example
#breweryData %>% filter(str_detect(Name,"Grain"))
#  Brew_ID Name                          City       State
#     <int> <chr>                         <chr>      <chr>
# 1       2 Against the Grain Brewery     Louisville KY   
# 2      63 Against The Grain Brewery     Louisville KY   
```

# Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.
```{r Aggregations by State, echo=TRUE}

beer_brewery_byState<-beer_brewery %>%
  group_by(State) %>%
  summarise(
    beer_count= n(),
    IBU_count = sum(!is.na(IBU)),
    IBU_average = mean(IBU, na.rm = TRUE),
    IBU_median = median(IBU, na.rm = TRUE),
    IBU_sd = sd(IBU, na.rm = TRUE),
    ABV_count = sum(!is.na(ABV)),
    ABV_average = mean(ABV, na.rm = TRUE),
    ABV_median = median(ABV, na.rm = TRUE),
    ABV_sd = sd(ABV, na.rm = TRUE),
    Number_of_breweries=length(unique(Brewery_name)),
    Number_of_styles=length(unique(Style))
  )

#add category counts for ABV_rating
beer_brewery_byState<-beer_brewery %>%
  filter(!is.na(ABV_rating)) %>% 
  count(State,ABV_rating) %>% 
  spread(ABV_rating,n, fill=0,sep = "_") %>%
  right_join(beer_brewery_byState, by="State")

#add category counts for IBU_rating
beer_brewery_byState<-beer_brewery %>%
  filter(!is.na(IBU_rating)) %>% 
  count(State,IBU_rating) %>% 
  spread(IBU_rating,n, fill=0,sep = "_") %>% 
  right_join(beer_brewery_byState, by="State") 

#add in population values
beer_brewery_byState<-beer_brewery_byState %>% 
  left_join(y=statepop_raw, by=c("State"="State_Abb")) %>% 
  select(c(-State_ID)) %>% 
  rename(State_name=State.y) %>% 
  mutate(breweries_per_million_person=(1000000*Number_of_breweries/Population))

#add in state area
beer_brewery_byState<-beer_brewery_byState %>% 
  left_join(y=statearea, by="State_name") %>% 
  mutate(breweries_per_million_sqmiles=(1000000*Square_miles/Population))


beer_brewery_byState 

```


```{r IBU Plots, echo=TRUE}
#barplot of median IBU by state, maybe do the top 10 and bottom 10 becuase it's crowded
beer_brewery_byState %>%
  arrange(IBU_median) %>% 
  mutate(State=factor(State, levels=State)) %>%
  head(10) %>% 
  ggplot(aes(x=State, y=IBU_median)) + geom_col()+ 
  labs(title="States with Highest IBU", 
       subtitle="")
  
beer_brewery_byState %>%
  arrange(desc(IBU_median)) %>% 
  mutate(State=factor(State, levels=State)) %>%
  head(10) %>% 
  ggplot(aes(x=State, y=IBU_median)) + geom_col() + 
  labs(title="States with Lowest IBU", 
       subtitle="")
```

```{r ABV Plots, echo=TRUE}
#barplot of median ABV by state, maybe do the top 10 and bottom 10 because it's crowded
beer_brewery_byState %>%
  arrange(ABV_median) %>% 
  mutate(State=factor(State, levels=State)) %>%
  head(10) %>% 
  ggplot(aes(x=State, y=ABV_median)) + geom_col() + 
  coord_flip()+ 
  labs(title="States with Highest ABV", 
       subtitle="")

  
beer_brewery_byState %>%
  arrange(desc(ABV_median)) %>% 
  mutate(State=factor(State, levels=State)) %>%
  head(10) %>% 
  ggplot(aes(x=State, y=ABV_median)) + geom_col() + 
  coord_flip() + 
  labs(title="States with Lowest ABV", 
       subtitle="")

```

```{r relationship between IBU and ABV, echo=TRUE}
beer_brewery %>% 
  ggplot(aes(x=IBU, y=ABV)) + geom_point()

```


# Which state has the maximum alcoholic (ABV) beer? 

```{r maximum alcoholic (ABV) beer, echo=TRUE}

#top 10 states for having high ABV beers
beer_brewery_byState %>% 
  arrange(desc(ABV_rating_high)) %>% 
  head(10)

```


# Which state has the most bitter (IBU) beer?

```{r most bitter(IBU) beer, echo=TRUE}

#top 10 states for having high IBU beers
beer_brewery_byState %>% 
  arrange(desc(IBU_rating_high)) %>% 
  head(10)
```


#Summary statistics for the ABV variable.

```{r summary statistics for the ABV variable, echo=TRUE}

summary(beerData$ABV)
hist(beerData$ABV)

```

